/**
 * Generated by orval v6.22.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type UserResponseRole =
  (typeof UserResponseRole)[keyof typeof UserResponseRole];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UserResponseRole = {
  USER: "USER",
  ADMIN: "ADMIN",
} as const;
